#!perl

use 5.010001;
use strict;
use warnings;

use App::FileRenameUtils qw(find_unique_filename);
use Cwd;
use File::Find;

# AUTHORITY
# DATE
# DIST
# VERSION

my $cwd = getcwd;

finddepth sub {
  #print "dir=$File::Find::dir\n";
  return if $File::Find::dir eq '.';
  return unless -f;
  my $filename = find_unique_filename("$cwd/$_");
  rename $_, $filename;
  print "$_ -> $filename\n";
}, ".";

# ABSTRACT: Move files in subdirectories to the current directory
# PODNAME:

=head1 DESCRIPTION

This utility will rename duplicates with the C< (n)> suffix, e.g.: F<foo.jpg>
into F<foo (1).jpg>, F<foo (2).jpg> and so on.


=head1 HISTORY

Packaged into App-FileRenameUtils as C<move-files-here>. Some enhancements.

First written as C<gather-files-here> on 2004-04-01.
