#!perl

use strict;
use warnings;
use Log::ger;
use Log::ger::Screen;

#use File::Which;

unless (@ARGV >= 1) {
    die "Usage: rename-add-prefix-number <FILE>...\n";
}
#die "rename-add-prefix-number: Can't find perlmv in PATH\n" unless which("perlmv");

my @args;
if (defined $ENV{DIGITS}) { push @args, "-a", "digits=".int($ENV{DIGITS}) }
push @args, @ARGV;
system "perlmv", "prefix-with-number", @args;

# ABSTRACT: Add serial number (1, 2, ...) to filenames
# PODNAME:

=head1 SYNOPSIS

 % rename-add-prefix-number [options] <file>...

Given these files:

 foo
 bar.txt

this command:

 % rename-add-prefix-number *

will rename them as follow:

 foo -> 1-foo
 bar.txt -> 2-bar.txt

When there are 10-99 files to rename, the numbers wilil be 01, 02, ... When
there are 100-999 files, the numbers will be 001, 002, ... and so on. But you
can force the number of digits using the C<DIGITS> environment variable.

You can use L<perlmv>'s options, e.g. C<-d> (dry-run), etc.


=head1 DESCRIPTION

This is a shortcut for:

 % perlmv prefix-with-number <file>...


=head1 ENVIRONMENT

=head2 DIGITS

Posint. Will be passed as the C<digits> argument to the
L<prefix-with-number|App::perlmv::scriptlet::prefix_with_number> scriptlet.


=head1 SEE ALSO

L<App::perlmv> and its L<App::perlmv::scriptlet::add_prefix_datestamp>
scriptlet.
