#!perl

use strict;
use warnings;
use Log::ger;
use Log::ger::Screen;

#use File::Which;

unless (@ARGV >= 1) {
    die "Usage: rename-with-number <FILE>...\n";
}
#die "rename-with-number: Can't find perlmv in PATH\n" unless which("perlmv");

my @args;
if (defined $ENV{DIGITS}) { push @args, "-a", "digits=".int($ENV{DIGITS}) }
if (defined $ENV{START}) { push @args, "-a", "start=".($ENV{START}+0) }
if (defined $ENV{INC}) { push @args, "-a", "inc=".($ENV{INC}+0) }
push @args, @ARGV;
system "perlmv", "with-number", @args;

# ABSTRACT: Rename files to serial number (1, 2, ...)
# PODNAME:

=head1 SYNOPSIS

 % rename-with-number [options] <file>...

Given these files:

 foo
 bar.txt

this command:

 % rename-with-number *

will rename them as follow:

 foo -> 1
 bar.txt -> 2.txt

When there are 10-99 files to rename, the numbers will be 01, 02, ... When
there are 100-999 files, the numbers will be 001, 002, ... and so on. But you
can force the number of digits using the C<DIGITS> environment variable.

You can use L<perlmv>'s options, e.g. C<-d> (dry-run), etc.


=head1 DESCRIPTION

This is a shortcut/wrapper for:

 % perlmv with-number <file>...


=head1 ENVIRONMENT

=head2 DIGITS

Posint. Will be passed as the C<digits> argument to the
L<with-number|App::perlmv::scriptlet::with_number> scriptlet. Default is to use
the necessary number of digits that fits the largest number used.

=head2 START

Float. Will be passed as the C<start> argument to the
L<with-number|App::perlmv::scriptlet::with_number> scriptlet. Default is 1.

=head2 INC

Float. Will be passed as the C<inc> argument to the
L<with-number|App::perlmv::scriptlet::with_number> scriptlet.
Default is 1.


=head1 SEE ALSO

L<App::perlmv>
