#!perl

use strict;
use warnings;
use Log::ger;
use Log::ger::Screen;

#use File::Which;
use IPC::System::Options 'system', -log=>1;

unless (@ARGV >= 1) {
    die "Usage: rename-add-prefix-datestamp <FILE>...\n";
}
#die "rename-add-prefix-datestamp: Can't find perlmv in PATH\n" unless which("perlmv");

system "perlmv", "add-prefix-datestamp", "-a", "avoid_duplicate_prefix=1", @ARGV;

# ABSTRACT: Add datestamp prefix (YYYYMMDD-) to filenames
# PODNAME:

=head1 SYNOPSIS

 % rename-add-prefix-datestamp [options] <file>...

Given these files:

 foo
 bar.txt

this command:

 % rename-add-prefix-datestamp *

will rename them as follow (the datestamp will use the file's modification
date):

 foo -> 20230110-foo
 bar.txt -> 20221223-bar.txt

Because this script is a wrapper for L<perlmv>, You can use C<perlmv>'s options,
e.g. C<-d> (dry-run), etc.


=head1 DESCRIPTION

This is a shortcut for:

 % perlmv add-prefix-datestamp -a avoid_duplicate_prefix=1 <file>...


=head1 SEE ALSO

L<App::perlmv> and its L<App::perlmv::scriptlet::add_prefix_datestamp>
scriptlet.
