#!perl

use strict;
use warnings;

use List::Util qw(shuffle);

unless (@ARGV >= 2) {
    die "rename-shuf: Please specify at least 2 files\n";
}

# make sure all files exist first
for (@ARGV) {
    die "rename-shuf: File '$_' doesn't exist\n" unless -e $_;
}

# create a temporary name that does not exist
my $tmp;
while (1) {
    $tmp = sprintf "rename-shuf-tmp-%d", rand()*1_000_000;
    last unless -e $tmp;
}

my @shuf_ARGV = shuffle @ARGV;

# start the shuffling!
for my $i (0 .. $#ARGV) {
    my $f1 = $ARGV[$i];
    my $f2 = $shuf_ARGV[$i];
    if ($f1 eq $f2) {
        print "Skipping swapping $f1 -> $f2 (same file)\n";
        next;
    }
    rename $f1, $tmp or die "rename-shuf: Can't rename $f1 -> $tmp: $!\n";
    rename $f2, $f1  or die "rename-shuf: Can't rename $f2 -> $f1: $!\n";
    rename $tmp, $f2 or die "rename-shuf: Can't rename $tmp -> $f2: $!\n";
    print "Swapping $f1 <-> $f2\n";
}

# PODNAME: rename-shuf
# ABSTRACT: Shuffle filenames

=head1 SYNOPSIS

 % rename-shuf f1 f2 f3 f4 f5


=head1 DESCRIPTION

WARNING: Be careful when running this script. This script does not support
dry-run (simulation) mode nor undo. It uses C<rename()> so it does not support
moving files across filesystems; it's best to specify only files in the same
directory.
